export const RELIC_NOTES = {
  liber: {
    title: 'Das Diktat',
    body: 'Drei Mittage in einem gemieteten Zimmer. Eine Stimme, die sich Boten nannte. Ich schrieb, was gesagt wurde, und nannte das Heft später ein Gesetz. Rose hatte recht gehabt: es ging um das Kind.',
  },
  athame: {
    title: 'Die Waffe der Luft',
    body: 'Stahl, der den Kreis schneidet. In der Theorie der Magick ist das Schwert der Verstand. Ich habe mehr Tinte vergossen als Blut — das Messer erinnert mich daran, dass der Wille eine Kante braucht.',
  },
  chalice: {
    title: 'Die Schale',
    body: 'Wasser, Wein, Empfängnis. Die Messe, die ich später schrieb, stellt die Schale der Priesterin gegenüber. Hier ist sie nur Kupfer und Stille am See.',
  },
  wand: {
    title: 'Der Wille als Stab',
    body: 'Feuer. Richtung. Im Tarot, den Frieda und ich malten, ist der Stab der erste Atem. Ohne ihn bleibt die Karte ein Bild.',
  },
  pantacle: {
    title: 'Die Scheibe',
    body: 'Erde. Entsprechungen. Ich habe einmal eine Tafel der Zahlen und Farben angelegt, siebenhundertundsiebzehn Zeilen und mehr. Diese Scheibe ist die kurze Fassung: was unten ist, bleibt unten, bis man es hebt.',
  },
  stele: {
    title: 'Die bemalte Platte',
    body: 'Im Museum zu Kairo eine Sargplatte eines Priesters. Rose zeigte darauf, bevor die Stimme kam. Ich ließ eine Kopie machen. Der Sandstein hier ist nicht dieselbe Platte. Er tut so.',
  },
  oil: {
    title: 'Das Rezept',
    body: 'Zimt, Myrrhe, Kalmus. Das Buch, das ich in Boleskine aufschlug, verlangt eine Salbe und sechs Monate Einsamkeit. Ich habe die Monate nicht gehalten. Das Fläschchen ist geblieben.',
  },
};

export const MEMORIES = [
  {
    id: 'manor',
    x: -42,
    z: 40,
    r: 16,
    title: 'Das Haus am See',
    whisper: 'Das Arbeitszimmer erinnert sich.',
    body: 'Ich kaufte das Haus, weil ein älterer Ritus einen abgelegenen Ort verlangt, mit einer Tür nach Norden und einem Wasser im Rücken. Vorher stand hier eine Kirche. Die Dorfbewohner hatten Geschichten. Ich habe sie nicht erfunden — ich habe sie bewohnt. Lord Boleskine, auf Visitenkarten.',
  },
  {
    id: 'spawn',
    x: -36.5,
    z: 24,
    r: 9,
    title: 'Leamington, und danach',
    whisper: 'Eine frühe Seite.',
    body: 'Edward Alexander, 1875, Plymouth Brethren, Geld aus Bier, das der Vater nicht trank. Als er starb, war ich elf und der Glaube ein leeres Zimmer. In Cambridge nannte ich mich Aleister. Schach, Berge, Verse. Der Rest kam später.',
  },
  {
    id: 'plaza',
    x: 0,
    z: 0,
    r: 14,
    title: 'Die Halle der Maurermeister',
    whisper: 'Das Pflaster kennt die Grade.',
    body: 'Im November 1898 nahm ich in der Isis-Urania einen Namen an: Perdurabo — ich werde ausharren. Mathers ließ mich weiter, Yeats wollte mich nicht. Das schwarzweiße Feld ist älter als wir beide. Die zwei Säulen stehen, auch wenn der Tempel nicht mehr tagt.',
  },
  {
    id: 'kirk',
    x: 90,
    z: 16,
    r: 14,
    title: 'Die abgerissene Kirche',
    whisper: 'Unter dem Fenster ein älterer Grundriss.',
    body: 'Boleskine steht auf einem Kirchplatz. Der Ritus, den ich hier begann, kommt aus einem deutschen Manuskript über einen ägyptischen Weisen. Sechs Monate, ein Kreis aus Sand, kein Besuch. Ich brach ab. Die Insel hat den Rest behalten.',
  },
  {
    id: 'cairo',
    x: -16,
    z: 44,
    r: 10,
    title: 'Drei Mittage',
    whisper: 'Drei Nischen, eine Stunde jede.',
    body: 'Kairo, Frühling 1904. Rose sagte, sie warteten. Am 8., 9. und 10. April, mittags, eine Stunde. Nuit, Hadit, das Kind. Ich war der Schreiber, nicht der Autor. Später verlegte ich das Heft und fand es wieder.',
  },
  {
    id: 'abbey',
    x: -80,
    z: -94,
    r: 16,
    title: 'Die Kommune',
    whisper: 'Rabelais hat den Namen geliehen.',
    body: '1920 mietete ich in Cefalù ein Haus und nannte es nach der Abtei in Gargantua. Leah führte den Haushalt und mehr. Die Wände wurden bemalt. 1923 wies uns die Regierung aus. Die Presse in London fand einen Titel für mich. Er klebt noch.',
  },
  {
    id: 'hollow',
    x: -68,
    z: 10,
    r: 12,
    title: 'Die Stimmen in der Wüste',
    whisper: 'Hier wird die Luft dünn.',
    body: '1909, Algerien, mit Neuburg. Dreißig Luftkreise eines älteren Systems. Im vorletzten begegnet man dem Wächter der Kluft. Ich habe das Protokoll veröffentlicht und es die Vision und die Stimme genannt. In Senken wie dieser hört man noch den Wind davon.',
  },
  {
    id: 'cairn',
    x: 98,
    z: -50,
    r: 12,
    title: 'Die Berge',
    whisper: 'Steine, geschichtet wie ein Lager.',
    body: 'Eckenstein hat mich das Seil gelehrt. Mexiko, die Alpen, der Versuch am Kangchendzönga, der schiefging. Ich bin ein besserer Magier als Führer gewesen. Der Steinhaufen verzeiht das nicht, er zählt nur, wer umkehrt.',
  },
  {
    id: 'chess',
    x: -30,
    z: 34,
    r: 7,
    title: 'Trinity',
    whisper: 'Eine offene Partie.',
    body: 'In Cambridge spielte ich, bis die Nacht um die Figuren zu eng wurde. Ich hätte Berufsspieler werden können. Stattdessen habe ich die Figuren in Grade übersetzt. Die Partie auf diesem Brett ist nicht zu Ende. Sie war es nie.',
  },
  {
    id: 'press',
    x: 26,
    z: -70,
    r: 8,
    title: 'Die Tag-und-Nacht-Gleiche',
    whisper: 'Ungebundene Bogen.',
    body: 'Ab 1909 stieß ich Hefte aus, zweimal im Jahr, und nannte sie nach der Gleichen. Fuller half, dann andere. Darin stand, was die A∴A∴ lehren sollte — ein silberner Stern, keine Kirche. Die Bogen hier haben keine Titel. Titel verderben die Auflage.',
  },
  {
    id: 'nether',
    x: 6,
    z: 86,
    r: 8,
    title: 'Hastings',
    whisper: 'Ein Stuhl zum Wasser.',
    body: '1947, ein Gästehaus, der Körper fertig. Ich habe mehr hinterlassen als die Zeitungen wollten: Verse, Tafeln, ein Kartenspiel mit Frieda, die Beichte eines Lebens, das ich Autohagiographie nannte. Der Stuhl sieht aufs Wasser. Das genügt als Schluss.',
  },
  {
    id: 'wood',
    x: -98,
    z: -14,
    r: 16,
    title: 'Der silberne Stern',
    whisper: 'Einsamkeit hat eine Regel.',
    body: 'Nach dem Bruch mit der alten Halle gründete ich mit Jones eine Arbeit, deren Buchstaben ein Stern sind. Kein Verein. Wer bleibt, bleibt. Der Wald hält dieselbe Regel.',
  },
  {
    id: 'pier',
    x: -20,
    z: 96,
    r: 12,
    title: 'Der See',
    whisper: 'Das Wasser behält Gerüchte.',
    body: 'Die Leute am Ness haben mir Ungeheuer angedichtet. Ich habe gelacht und nicht widersprochen. Ein See braucht eine Geschichte. Dieser hat mehrere, und ich bin nur eine davon.',
  },
  {
    id: 'vault',
    x: 24,
    z: -22,
    r: 9,
    title: 'Sieben Wände',
    whisper: 'Ein Grad ohne Zeremonie.',
    body: 'Im inneren Orden der alten Halle stand ein siebenseitiger Raum, Farben gegeneinander gesetzt, damit das Auge blitzt. Ich bin dort aufgenommen worden, gegen den Willen der Londoner. Die Kammer hier ist nur der Grundriss. Der Rest ist Licht.',
  },
  {
    id: 'willow',
    x: 74,
    z: 46,
    r: 8,
    title: 'Die Salbe',
    whisper: 'Drei Harze, ein Jahr, das ich nicht hielt.',
    body: 'Das Rezept steht in dem Buch, das ich am See aufschlug. Die Weide ist der falsche Baum dafür und trotzdem der richtige Ort: etwas tropft, jemand hat aufgefangen.',
  },
];

export const ENDING = {
  title: 'Die Unterredung',
  body: 'Nicht der Mond öffnet sich. Etwas, das ich den Heiligen Schutzengel genannt habe — und das Buch einen Stern in jedem Mann und jeder Frau. Das Gesetz bleibt ein Satz, den ich nicht erfunden habe. Die Arbeit hält, solange man sie tut.',
};
