export const RELIC_NOTES = {
  liber: {
    title: 'Das Diktat',
    body: 'Drei Mittage in einem gemieteten Zimmer. Eine Stimme, die sich Boten nannte. Ich schrieb, was gesagt wurde, und nannte das Heft später ein Gesetz. Rose hatte recht gehabt: es ging um das Kind.',
  },
  athame: {
    title: 'Die Waffe der Luft',
    body: 'Stahl, der den Kreis schneidet. In der Theorie der Magick ist das Schwert der Verstand. Ich habe mehr Tinte vergossen als Blut — das Messer erinnert mich daran, dass der Wille eine Kante braucht.',
  },
  chalice: {
    title: 'Die Schale',
    body: 'Wasser, Wein, Empfängnis. Die Messe, die ich später schrieb, stellt die Schale der Priesterin gegenüber. Hier ist sie nur Kupfer und Stille über dem Staub.',
  },
  wand: {
    title: 'Der Wille als Stab',
    body: 'Feuer. Richtung. Im Tarot, den Frieda und ich malten, ist der Stab der erste Atem. Ohne ihn bleibt die Karte ein Bild.',
  },
  pantacle: {
    title: 'Die Scheibe',
    body: 'Erde. Entsprechungen. Ich habe einmal eine Tafel der Zahlen und Farben angelegt, siebenhundertundsiebzehn Zeilen und mehr. Diese Scheibe ist die kurze Fassung: was unten ist, bleibt unten, bis man es hebt.',
  },
  stele: {
    title: 'Die bemalte Platte',
    body: 'Im Museum zu Kairo eine Sargplatte eines Priesters. Rose zeigte darauf, bevor die Stimme kam. Ich ließ eine Kopie machen. Der Sandstein hier ist nicht dieselbe Platte. Er tut so.',
  },
  oil: {
    title: 'Das Rezept',
    body: 'Zimt, Myrrhe, Kalmus. Das Buch, das ich in Boleskine aufschlug, verlangt eine Salbe und sechs Monate Einsamkeit. Ich habe die Monate nicht gehalten. Das Fläschchen ist geblieben.',
  },
};

export const MEMORIES = [
  {
    id: 'manor',
    x: -42,
    z: 40,
    r: 16,
    title: 'Das Haus am See',
    whisper: 'Das Arbeitszimmer erinnert sich.',
    body: 'Ich kaufte das Haus, weil ein älterer Ritus einen abgelegenen Ort verlangt, mit einer Tür nach Norden und einem Wasser im Rücken. Vorher stand hier eine Kirche. Die Dorfbewohner hatten Geschichten. Ich habe sie nicht erfunden — ich habe sie bewohnt. Lord Boleskine, auf Visitenkarten.',
  },
  {
    id: 'spawn',
    x: -36.5,
    z: 24,
    r: 9,
    title: 'Leamington, und danach',
    whisper: 'Eine frühe Seite.',
    body: 'Edward Alexander, 1875, Plymouth Brethren, Geld aus Bier, das der Vater nicht trank. Als er starb, war ich elf und der Glaube ein leeres Zimmer. In Cambridge nannte ich mich Aleister. Schach, Berge, Verse. Der Rest kam später.',
  },
  {
    id: 'plaza',
    x: 0,
    z: 0,
    r: 14,
    title: 'Die Halle der Maurermeister',
    whisper: 'Das Pflaster kennt die Grade.',
    body: 'Im November 1898 nahm ich in der Isis-Urania einen Namen an: Perdurabo — ich werde ausharren. Mathers ließ mich weiter, Yeats wollte mich nicht. Das schwarzweiße Feld ist älter als wir beide. Die zwei Säulen stehen, auch wenn der Tempel nicht mehr tagt.',
  },
  {
    id: 'kirk',
    x: 90,
    z: 16,
    r: 14,
    title: 'Die abgerissene Kirche',
    whisper: 'Unter dem Fenster ein älterer Grundriss.',
    body: 'Boleskine steht auf einem Kirchplatz. Der Ritus, den ich hier begann, kommt aus einem deutschen Manuskript über einen ägyptischen Weisen. Sechs Monate, ein Kreis aus Sand, kein Besuch. Ich brach ab. Die Insel hat den Rest behalten.',
  },
  {
    id: 'cairo',
    x: -16,
    z: 44,
    r: 10,
    title: 'Drei Mittage',
    whisper: 'Drei Nischen, eine Stunde jede.',
    body: 'Kairo, Frühling 1904. Rose sagte, sie warteten. Am 8., 9. und 10. April, mittags, eine Stunde. Nuit, Hadit, das Kind. Ich war der Schreiber, nicht der Autor. Später verlegte ich das Heft und fand es wieder.',
  },
  {
    id: 'abbey',
    x: -80,
    z: -94,
    r: 16,
    title: 'Die Kommune',
    whisper: 'Rabelais hat den Namen geliehen.',
    body: '1920 mietete ich in Cefalù ein Haus und nannte es nach der Abtei in Gargantua. Leah führte den Haushalt und mehr. Die Wände wurden bemalt. 1923 wies uns die Regierung aus. Die Presse in London fand einen Titel für mich. Er klebt noch.',
  },
  {
    id: 'hollow',
    x: -68,
    z: 10,
    r: 12,
    title: 'Die Stimmen in der Wüste',
    whisper: 'Hier wird die Luft dünn.',
    body: '1909, Algerien, mit Neuburg. Dreißig Luftkreise eines älteren Systems. Im vorletzten begegnet man dem Wächter der Kluft. Ich habe das Protokoll veröffentlicht und es die Vision und die Stimme genannt. In Senken wie dieser hört man noch den Wind davon.',
  },
  {
    id: 'cairn',
    x: 98,
    z: -50,
    r: 12,
    title: 'Die Berge',
    whisper: 'Steine, geschichtet wie ein Lager.',
    body: 'Eckenstein hat mich das Seil gelehrt. Mexiko, die Alpen, der Versuch am Kangchendzönga, der schiefging. Ich bin ein besserer Magier als Führer gewesen. Der Steinhaufen verzeiht das nicht, er zählt nur, wer umkehrt.',
  },
  {
    id: 'chess',
    x: -30,
    z: 34,
    r: 7,
    title: 'Trinity',
    whisper: 'Eine offene Partie.',
    body: 'In Cambridge spielte ich, bis die Nacht um die Figuren zu eng wurde. Ich hätte Berufsspieler werden können. Stattdessen habe ich die Figuren in Grade übersetzt. Die Partie auf diesem Brett ist nicht zu Ende. Sie war es nie.',
  },
  {
    id: 'press',
    x: 26,
    z: -70,
    r: 8,
    title: 'Die Tag-und-Nacht-Gleiche',
    whisper: 'Ungebundene Bogen.',
    body: 'Ab 1909 stieß ich Hefte aus, zweimal im Jahr, und nannte sie nach der Gleichen. Fuller half, dann andere. Darin stand, was die A∴A∴ lehren sollte — ein silberner Stern, keine Kirche. Die Bogen hier haben keine Titel. Titel verderben die Auflage.',
  },
  {
    id: 'nether',
    x: 6,
    z: 86,
    r: 8,
    title: 'Hastings',
    whisper: 'Ein Stuhl zum Wasser.',
    body: '1947, ein Gästehaus, der Körper fertig. Ein Jüngerer hat Monate lang für mich geschrieben, ohne Lohn, gegen Unterricht. Die Familie holte ihn weg. Ich habe mehr hinterlassen als die Zeitungen wollten: Verse, Tafeln, ein Kartenspiel mit Frieda, die Beichte eines Lebens. Der Stuhl sieht auf die dunkle Ebene. Das genügt als Schluss.',
  },
  {
    id: 'wood',
    x: -98,
    z: -14,
    r: 16,
    title: 'Der silberne Stern',
    whisper: 'Einsamkeit hat eine Regel.',
    body: 'Nach dem Bruch mit der alten Halle gründete ich mit Jones eine Arbeit, deren Buchstaben ein Stern sind. Kein Verein. Wer bleibt, bleibt. Der Wald hält dieselbe Regel.',
  },
  {
    id: 'pier',
    x: -20,
    z: 96,
    r: 12,
    title: 'Der Staubkai',
    whisper: 'Die Ebene behält Gerüchte.',
    body: 'Die Leute am Ness haben mir Ungeheuer angedichtet. Hier ist kein See mehr, nur eine dunkle Fläche, die sich wie Wasser legt. Ein Planet braucht eine Geschichte. Dieser hat mehrere, und ich bin nur eine davon.',
  },
  {
    id: 'vault',
    x: 24,
    z: -22,
    r: 9,
    title: 'Sieben Wände',
    whisper: 'Ein Grad ohne Zeremonie.',
    body: 'Im inneren Orden der alten Halle stand ein siebenseitiger Raum, Farben gegeneinander gesetzt, damit das Auge blitzt. Ich bin dort aufgenommen worden, gegen den Willen der Londoner. Die Kammer hier ist nur der Grundriss. Der Rest ist Licht.',
  },
  {
    id: 'willow',
    x: 74,
    z: 46,
    r: 8,
    title: 'Die Salbe',
    whisper: 'Drei Harze, ein Jahr, das ich nicht hielt.',
    body: 'Das Rezept steht in dem Buch, das ich am See aufschlug. Die Weide ist der falsche Baum dafür und trotzdem der richtige Ort: etwas tropft, jemand hat aufgefangen.',
  },
  {
    id: 'iron',
    x: -260,
    z: -53,
    r: 14,
    title: 'Fünf',
    whisper: 'Eisen hat eine Zahl.',
    body: 'Im alten Schema gehört der rote Planet zur fünften Sephira: Härte, Gericht, das Metall, das nicht biegt. Ich habe die Tafel nicht erfunden. Ich habe sie abgeschrieben. Fünf Steine reichen, wenn man nicht predigen will.',
  },
  {
    id: 'crater',
    x: 319,
    z: -73,
    r: 16,
    title: 'Die Schale im Stein',
    whisper: 'Ein Auge ohne Tempel.',
    body: 'Manche Krater sehen aus wie eine Schale, die niemand reicht. Das Zeichen auf dem Boden ist Eisen, nicht Tinte. Das Auge darüber ist älter als mein Ägypten — oder jünger, und tut nur so. Beides ist brauchbar.',
  },
  {
    id: 'cydonia',
    x: 283,
    z: 41,
    r: 18,
    title: 'Der Hang, der blickt',
    whisper: 'Ein Gesicht aus Stunde und Schatten.',
    body: 'Es gibt Hügel, die ein Gesicht sind, sobald die Sonne niedrig steht, und wieder keiner, wenn sie steigt. Ich habe Götter aus weniger gemacht. Hier bleibt man stehen, nicht weil jemand ruft, sondern weil der Hang zurücksieht.',
  },
  {
    id: 'polar',
    x: 212,
    z: 142,
    r: 12,
    title: 'Die weiße Kappe',
    whisper: 'Kälte hat eine Regel.',
    body: 'An den Polen schmilzt nichts, das man rufen könnte. Sieben kleine Lichter, ein Kreuz mit Henkel. Wer hierher kommt, kommt ohne Gemeinde. Das habe ich in der Wüste gelernt, und der Schnee sagt dasselbe leiser.',
  },
  {
    id: 'orrery',
    x: 236,
    z: 59,
    r: 12,
    title: 'Die Bahnen',
    whisper: 'Eine Uhr ohne Stunden.',
    body: 'Die Kanäle, die man von der Erde aus zu sehen glaubte, waren ein Wunsch: dass jemand dort zählt wie wir. Die Ringe hier zählen trotzdem. Stunde, Planet, Entsprechung. Ich habe davon Tafeln gemacht. Die Ringe brauchen keine.',
  },
  {
    id: 'seal',
    x: -218,
    z: 65,
    r: 10,
    title: 'Das ungesiegelte Siegel',
    whisper: 'Fünf Kanten, eine Glut.',
    body: 'Ein Siegel, das niemand in Wachs drückt. Die Form genügt. In der Korrespondenz ist fünf die Zahl des Krieges und der Härte — und hier nur ein Pflaster, auf dem man stehen kann, ohne zu knien.',
  },
  {
    id: 'fullness',
    x: 48,
    z: -12,
    r: 11,
    title: 'Licht, Leben, Liebe, Freiheit',
    whisper: 'Die Kirche ohne Gemeinde.',
    body: 'Ich habe eine Messe geschrieben und sie gnostisch genannt, weil das Wort älter ist als die, die es verwaltet haben. Nicht Glaube. Kenntnis. Eine Fülle, die man nicht füllt, sondern erkennt. Die sieben Lichter hier predigen nicht. Sie stehen.',
  },
  {
    id: 'daath',
    x: 38,
    z: -28,
    r: 10,
    title: 'Die elfte, die keine ist',
    whisper: 'Eine Kachel fehlt.',
    body: 'Zehn sind sichtbar. Zwischen Weisheit und Schönheit lassen die Diagramme eine Stelle leer. Ich habe sie die Schwelle zur Kluft genannt, nicht den elften Grad. Wer hier steht, steht nicht auf einem Pfad. Er steht in der Lücke.',
  },
  {
    id: 'lam',
    x: 10.4,
    z: 88.6,
    r: 8,
    title: 'Der Lama',
    whisper: 'Ein Gesicht, das keiner bestellt hat.',
    body: 'In New York, 1918, eine Arbeit, die ich Amalantrah nannte. Ein Kopf kam, eiförmig, die Augen zu weit. Ich nannte ihn den Lama und zeichnete ihn. In Hastings nahm ein Jüngerer das Blatt. Es hatte ihn gewählt, sagte er. Ich habe nicht widersprochen.',
  },
  {
    id: 'mauve',
    x: -305,
    z: 22,
    r: 14,
    title: 'Zwischen zwei Schläfen',
    whisper: 'Die Farbe hält nicht still.',
    body: 'Es gibt einen Streifen zwischen Traum und traumlosem Schlaf, den ich nicht benannt habe. Der Jüngere, der in Hastings für mich schrieb, nannte später eine Zone danach — mauve, weder wach noch tot. Hier ist nur Staub, der sich so färbt. Das genügt als Hinweis.',
  },
  {
    id: 'nisis',
    x: -148,
    z: 118,
    r: 14,
    title: 'Elf, und draußen',
    whisper: 'Ein Schleier, elf Lichter.',
    body: 'Nuit sagt, ihre Zahl sei elf. Isis ist der Raum, den die Sterne erhellen; Nuit ist der Raum dahinter. Ein Jüngerer hat daraus eine Loge gemacht und einen Planeten jenseits von Pluto dazu erdacht. Ich habe den Satz geliefert. Das Haus hat er gestellt.',
  },
  {
    id: 'cells',
    x: 168,
    z: -118,
    r: 14,
    title: 'Zweiundzwanzig Zellen',
    whisper: 'Die Rückseite des Baums.',
    body: 'In einem Heft, das ich 231 nannte, stehen Zeichen für die Zellen unter den Pfaden. Ich habe sie gezeichnet, nicht begangen. Wer die Nachtseite des Gartens sucht, sucht hier. Die Zellen sind leer. Das ist ihre Arbeit.',
  },
  {
    id: 'marks',
    x: -88,
    z: 22,
    r: 9,
    title: 'Weder-weder',
    whisper: 'Zeichen ohne Namen.',
    body: 'Ein Maler in Southwark, arm, genau. Er nannte eine Methode, bei der das Bild sich selbst vergisst. Der Jüngere hat ihn später wieder ins Licht geschoben. Die Striche an dieser Wand gehören keinem Alphabet. Deshalb halten sie.',
  },
  {
    id: 'mile',
    x: -18,
    z: 12,
    r: 8,
    title: 'Der erste Stein',
    whisper: 'Ein Schritt zählt.',
    body: 'Zwischen Haus und Hof habe ich einen Stein gesetzt, der nichts behauptet. Nur: hier war jemand. Die Grade fangen nicht im Tempel an. Sie fangen, wo man stehen bleibt und merkt, dass man gegangen ist.',
  },
  {
    id: 'tworoads',
    x: 6,
    z: -44,
    r: 8,
    title: 'Zwei Wege',
    whisper: 'Keiner ist falsch. Einer ist früher.',
    body: 'Dorf oder Presse, Kürbis oder Bogen. Ich habe beide genommen, nur nicht am selben Tag. Wer an dieser Gabel zögert, hat schon gewählt: er bleibt und liest die Pfosten.',
  },
  {
    id: 'ink',
    x: 20,
    z: -78,
    r: 8,
    title: 'Die Klecksgrube',
    whisper: 'Tinte hält länger als Auflage.',
    body: 'Die Hefte der Gleichen sind woanders gebunden. Hier ist nur der Rest: ein Topf, der umfiel, und ein Fleck, der sich für wichtig hält. Ich habe aus solchen Flecken Gesetze gemacht. Das ist keine Empfehlung.',
  },
  {
    id: 'mothwell',
    x: -80,
    z: -4,
    r: 8,
    title: 'Der Mottenbrunnen',
    whisper: 'Licht, das sich irrt.',
    body: 'Motten nehmen die Lampe für den Mond. Magier nehmen den Mond für eine Anweisung. Der Brunnen hält beides aus. Wer hineinsieht, sieht zuerst sich, dann das Gold, dann nichts. Die Reihenfolge ist die Lehre.',
  },
  {
    id: 'bonegate',
    x: -82,
    z: 8,
    r: 8,
    title: 'Das Knochentor',
    whisper: 'Ein Durchgang ohne Tür.',
    body: 'Zwei Pfosten, eine Schwelle aus Luft. In der Senke daneben habe ich mit Neuburg diktiert. Hier habe ich nur durchgesehen. Manche Grade sind ein Gehen, keine Formel. Der Knochen erinnert daran, wer zuletzt geht.',
  },
  {
    id: 'ashrow',
    x: 82,
    z: 32,
    r: 8,
    title: 'Die Aschenreihe',
    whisper: 'Sieben, und keiner mit Namen.',
    body: 'Zwischen Kirche und Weide stehen sieben Steine, die niemand gesetzt haben will. Asche braucht keine Inschrift. Ich habe Tote mit Titeln versehen. Die Reihe hier hat recht: sie schweigt besser als ich.',
  },
  {
    id: 'redcamp',
    x: -180,
    z: -20,
    r: 10,
    title: 'Das rostige Lager',
    whisper: 'Jemand kehrte nicht um.',
    body: 'Ein Rumpf, ein Fass, eine kalte Feuerstelle. Die Nachtseite hat Bewohner gehabt, oder Durchreisende. Ich habe Lager in Mexiko und am Kangchendzönga gesehen. Dieses hier zählt nicht den Gipfel. Es zählt das Bleiben.',
  },
  {
    id: 'silent',
    x: -238,
    z: 8,
    r: 9,
    title: 'Die stille Meile',
    whisper: 'Eine Nadel im Staub.',
    body: 'Eisen, dünn, ohne Fahne. Zwischen Siegel und Kreis braucht die Ebene einen Punkt, sonst verläuft das Auge. Ich habe Nadeln in Diagramme gesetzt und sie Sephiroth genannt. Diese hier nennt sich nicht.',
  },
  {
    id: 'stargaze',
    x: 224,
    z: 100,
    r: 10,
    title: 'Die Nachtwache',
    whisper: 'Zwölf Steine, ein Stift.',
    body: 'Wer die Bahnen zählen will, legt erst einen Kreis. Zwölf ist älter als sieben, und ungenauer. Zwischen Uhr und Kappe steht die Nadel und behauptet Norden. Auf einer Kugel ist das eine Höflichkeit.',
  },
  {
    id: 'dustchoir',
    x: 240,
    z: -96,
    r: 10,
    title: 'Der Staubchor',
    whisper: 'Fünf Stimmen, kein Text.',
    body: 'Zwischen Krater und Zellen lehnen fünf Platten wie Sänger, die den Einsatz verpasst haben. Ich habe Chöre geleitet, die schlechter schwiegen. Hier ist die Partitur der Wind. Man bleibt, bis man merkt, dass man mithört.',
  },
];

export const ENDING = {
  title: 'Die Unterredung',
  body: 'Nicht der Mond öffnet sich. Etwas, das ich den Heiligen Schutzengel genannt habe — und das Buch einen Stern in jedem Mann und jeder Frau. Das Gesetz bleibt ein Satz, den ich nicht erfunden habe. Die Arbeit hält, solange man sie tut.',
};
